version: "3"

volumes:
   _postgres_data:

services:
  db:
    image: postgres:13
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  migrations:
    build: .
    profiles:
      - 'migrations'
    volumes:
      - ./:/code/
    env_file:
      - .env
    command: python manage.py migrate --noinput
    depends_on:
      - db
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/code/
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      - migrations
      - db
